name: F5 Ansible CI

on:
  pull_request:
  push:

jobs:
  build:
    name: Build bigip on Ansible ${{ matrix.ansible }} (Python ${{ matrix.python-version }})
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        ansible:
          - stable-2.14
          - devel
        python-version:
          - 3.8
          - 3.9
          - "3.10"
          - "3.11"
        exclude:
          - python-version: 3.8
            ansible: stable-2.14
          - python-version: 3.8
            ansible: devel
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python${{ matrix.python }} -m pip install --upgrade pip
        python${{ matrix.python }} -m pip install https://github.com/ansible/ansible/archive/${{ matrix.ansible }}.tar.gz --disable-pip-version-check
        python${{ matrix.python }} -m pip install -r ansible_collections/f5networks/f5_bigip/requirements.txt --upgrade

    - name: Run sanity tests
      run: |
        cd ansible_collections/f5networks/f5_bigip/
        ansible-test sanity --color yes -v --requirements --docker
